# Generated by Django 4.1.2 on 2023-06-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_auto_20221009_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '题目管理', 'verbose_name_plural': '题目管理'},
        ),
        migrations.AlterModelOptions(
            name='questionset',
            options={'verbose_name': '题库管理', 'verbose_name_plural': '题库管理'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='active',
            field=models.BooleanField(default=True, verbose_name='发布'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_difficulty',
            field=models.IntegerField(choices=[(-1, '未知'), (0, '简单'), (1, '中等'), (2, '困难'), (3, '挑战')], default=-1, verbose_name='题目难度'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='create_sql',
            field=models.TextField(verbose_name='创建库表 & 数据初始化SQL'),
        ),
    ]
